name: Doppler Secrets
description: Fetch secrets from Doppler

inputs:
  doppler-token:
    description: Doppler token
    required: true
  doppler-project:
    description: Doppler project
    required: true
  doppler-config:
    description: Doppler config
    required: true
  secrets:
    description: List of secrets to fetch, separated by newlines
    required: true

runs:
  using: node12
  main: index.js
